#!/bin/bash

# excerpted from zclassic/zutil/init-mac.sh

if [ ! -f "$HOME/Library/Application Support/zelcash/zelcash.conf" ]; then
	echo "Creating zelcash.conf"
	mkdir -p "$HOME/Library/Application Support/zelcash/"
	echo "rpcuser=zelcashrpc" > ~/Library/Application\ Support/zelcash/zelcash.conf
	PASSWORD=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
	echo "rpcpassword=$PASSWORD" >> "$HOME/Library/Application Support/zelcash/zelcash.conf"
	echo "Complete!"
fi
